---
- name: Install Cockpit
  hosts: all
  become: yes
  become_method: sudo
 
  tasks:
  - name: Update repositories cache
    apt:
      update_cache: yes

  - name: Install cockpit
    apt:
      name: cockpit
      state: present
